incTemplate = """/*
    Auto Generated by Tizzy
    $version
    $website
    ===================================
    Input File:    $filename
    Generated on:  $creation_date
*/

localparam
$state_params
"""
